import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import { useQuery } from '@apollo/client'
import { GET_COIN_GQL } from '../src/lib/queries'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data, loading, error } = useQuery(GET_COIN_GQL, {
    variables: { coin: 'btc' },
    pollInterval: 30000, // Refresh every 30 seconds
  });

  return (
    <>
      <Head>
        <title>Create LunarCrush App</title>
        <meta name="description" content="Generated by create-lunarcrush-app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>

              href="https://lunarcrush.com/developers"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <span className={styles.logo}>
                LunarCrush
              </span>
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <p className={styles.description}>
            Connected to LunarCrush GraphQL API
          </p>
        </div>

        <div className={styles.grid}>
          {/* Bitcoin Data Example */}
          <div className={styles.card}>
            <h2>
              Bitcoin Data <span>-&gt;</span>
            </h2>
            {loading && <p>Loading Bitcoin data...</p>}
            {error && <p>Error: {error.message}</p>}
            {data && data.getCoin && (
            <div className="text-sm opacity-70">
              <p><strong>Price:</strong> \${data.getCoin.price?.toLocaleString()}</p>
              <p><strong>24h Change:</strong> {data.getCoin.percent_change_24h}</p>
              <p><strong>Galaxy Score:</strong> {data.getCoin.galaxy_score}</p>
              <p><strong>Alt Rank:</strong> {data.getCoin.alt_rank}</p>
              <p className="mt-2 text-xs opacity-50">Updates every 30 seconds</p>
            </div>
          )}
          </div>

          {/* Developer Info Card */}
          <div className={styles.card}>
            <h2>
              Developer Tools <span>-&gt;</span>
            </h2>
            <p>Explore the GraphQL API and documentation.</p>
            <div style={{ marginTop: '1rem' }}>
              <a
                href="https://lunarcrush-universal-backend.cryptoguard-api.workers.dev/graphql"
                target="_blank"
                rel="noopener noreferrer"
                style={{ display: 'block', marginBottom: '0.5rem', color: '#0070f3' }}
              >
                🚀 GraphQL Playground
              </a>
              <a
                href="https://lunarcrush.com/developers"
                target="_blank"
                rel="noopener noreferrer"
                style={{ display: 'block', color: '#0070f3' }}
              >
                📚 LunarCrush Docs
              </a>
            </div>
          </div>

          <div className={styles.card}>
            <h2>
              API Status <span>-&gt;</span>
            </h2>
            <p>Connection status and usage information.</p>
            <div style={{ marginTop: '1rem' }}>
              <p><strong>Endpoint:</strong> GraphQL</p>
              <p><strong>Status:</strong> {loading ? '🟡 Loading' : error ? '🔴 Error' : '🟢 Connected'}</p>
              <p><strong>Update:</strong> Every 30s</p>
              <p><strong>Auth:</strong> No API key required</p>
            </div>
          </div>

          <div className={styles.card}>
            <h2>
              Next Steps <span>-&gt;</span>
            </h2>
            <p>Build your crypto social trading application.</p>
            <div style={{ marginTop: '1rem', fontSize: '0.9rem' }}>
              <p>• Add more crypto symbols</p>
              <p>• Query creator data</p>
              <p>• Display sentiment analysis</p>
              <p>• Build real-time alerts</p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
